---
# Role installs web server nginx.

# Install light version of nginx.
# Debian like distros seem to have this one.

- name: nginx-light present
  apt: name={{ item }}
       state=present
       install_recommends=no
  with_items:
    - nginx
  notify:
    - nginx start
  tags:
    - packages
    - nginx
