---
# TODO Check these contribs: https://github.com/mivok/ansible-hosts, https://github.com/weareinteractive/ansible-hosts
- name: adding dev VMs host entries to all hosts
  hosts: ansible:dev-vms-web
  sudo: yes
  roles:
    - { role: hostname, when: apply_hostname }
    - hosts
    - { role: reboot,
        when: inventory_hostname != "debian-sid.vbox.com"
              and reboot_hosts and apply_hostname
      }
  vars:
    apply_hostname: false
    reboot_hosts: true
    hosts_reset: true
    hosts:
      - { ip: '192.168.10.100', domain: 'dev-1.pivanov.vm' }
      - { ip: '192.168.10.101', domain: 'dev-2.pivanov.vm' }
      - { ip: '192.168.10.102', domain: 'dev-3.pivanov.vm' }
      - { ip: '192.168.10.100', domain: 'debian-sid.vbox.com' }
      - { ip: '192.168.10.101', domain: 'ubuntu-tahr.vbox.com' }
      - { ip: '192.168.10.102', domain: 'ubuntu-vervet.vbox.com' }
