---
# Setup development machines for web.

- name: setup development environments
  hosts: dev-vms-web
# Inventory level setting ansible_ssh_user seems to overwrite remote_user.
#  remote_user: darko
# Run all tasks using sudo
  sudo: yes
# as the given user.
#  sudo_user: www-data
#
  roles:
    - common
    - samba
    - nginx

# Example of some Jinja2 filters.
#  vars:
#    - var: "\"'`"
#  tasks:
#    - name: replace test
#      shell: "/bin/echo {{ var|regex_replace('[\"\\'`]', 'q') }}"
#      register: res
#      changed_when: (res.rc == 0 and res.stdout|search("q")) != true

# @fixme Since prompts are not allowed in roles, create a special play for pass.
#  vars_prompt:
#  - name: samba_pass
#    prompt: "samba dev user password"
#    private: yes
#    confirm: yes
#    tags:
#      - config
#      - samba
