---
# Start nginx.
- name: nginx start
  service: name=nginx state=started

# Stop nginx.
- name: nginx stop
  service: name=nginx state=stopped

# Restart nginx.
- name: nginx restart
  service: name=nginx state=restarted

# Reload nginx.
# When configurations changed and can be applied. Note that
# if there's a syntax error in the config files, nginx will
# continue working with the old configuration.
- name: nginx reload
  service: name=nginx state=reloaded

# Start samba.
- name: samba start
  service: name=smbd state=started

# Restart samba.
- name: samba restart
  service: name=smbd state=restarted

# Start MySQL.
- name: mysql start
  service: name=mysql state=started

# Restart MySQL.
- name: mysql restart
  service: name=mysql state=restarted

# Start PHP 5 FPM.
- name: php5-fpm start
  service: name=php5-fpm state=started

# Restart MySQL.
- name: php5-fpm restart
  service: name=php5-fpm state=restarted
