---
# Role installs MySQL RDBMS.

- name: mysql present
  apt: name={{ item }}
       state=present
       install_recommends=no
  with_items:
    - mysql-server-5.5
  notify:
    - mysql start
  tags:
    - packages
    - mysql
