---
# Install common packages.

- name: base packages
  apt: name={{ item }}
       state=present
       install_recommends=no
  with_items:
    - bash
    - make
    - htop
    - ispell
    - git
  tags:
    - common
    - packages
    - apt

# First install the emacs*-nox version so the later emacs
# package doesn't drag in the whole X system.
- name: emacs nox
  apt: name=emacs24-nox
       state=present
  tags:
    - common
    - packages
    - apt
    - emacs

- name: emacs commons
  apt: name={{ item }}
  with_items:
    - emacs
    - emacs-goodies-el
  tags:
    - common
    - packages
    - apt
    - emacs
